version: '3.1'

services:
  discovery-service:
    build: ./discovery-service
    restart: always
    environment:
      - eureka.login=${eureka_login}
      - eureka.password=${eureka_password}
      - server.port=${eureka_port}
    ports:
      - 8080:${eureka_port}

  business-service:
    build: ./business-service
    restart: always
    environment:
      - eureka.login=${eureka_login}
      - eureka.password=${eureka_password}
      - eureka.url=${eureka_url}
      - eureka.port=${eureka_port}
      - server.port=${business_service_port}
    ports:
      - 8081:${business_service_port}
    links:
      - discovery-service:${eureka_url}

  gateway-service:
    build: ./gateway-service
    restart: always
    environment:
      - eureka.login=${eureka_login}
      - eureka.password=${eureka_password}
      - eureka.url=${eureka_url}
      - eureka.port=${eureka_port}
      - server.port=${gateway_service_port}
    ports:
      - 8082:${gateway_service_port}
    links:
      - discovery-service:${eureka_url}
